name: signup_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  json_annotation: ^4.8.0
  json_serializable: ^6.7.0
  sqlite3: ^2.2.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^5.0.0
  test: ^1.24.0
